name: dartStudy
description: A sample command-line application.
version: 1.0.0
homepage: https://www.example.com
author: denglt <ltdeng@hotmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

executables:
  hello_world:

dependencies:
#  path: ^1.4.1
  meta: ^1.1.7
  html:
  markdown: ^2.0.3  
  
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
